### ISSUE TITLE
Line charts, version 1.0: Smooth issues?

### ISSUE THREAD

**Issue by mdhampton** [apexcharts/Blazor-ApexCharts#289] opened 2023-09-18 14:08 UTC
It seems that the smooth line option only works for the first series. As an example, see the line chart examples in the demo application, DataLabels example. Second series has no lines, just the datapoints. You can also duplicate this by adding option to the Basic chart, and have just the Stroke property set to { Curve = Curve.Smooth }

**Comment by joadan** [comment] 2023-09-18 17:36
Thanks for reporting..

I'll look into it now.

**Comment by joadan** [comment] 2023-09-18 18:39
@thirstyape, What do you think about this one?

The problem is that currently we only have json converters for `ValueOrList<string>, ValueOrList<double>`.
This is an enum and that is why we fail. 

if we add a converter for Curve like  
` serializerOptions.Converters.Add(new ValueOrListConverter<Curve>());`

It will work but we would have to add a converter for each enum.

**Comment by thirstyape** [comment] 2023-09-18 18:54
I think adding converters for each enum used in the /MultiType folder is the way to go. There should not be any noticeable performance change as it is a static dictionary.

**Comment by joadan** [comment] 2023-09-18 18:56
Ok, I'll add them.

Thank you

**Comment by joadan** [comment] 2023-09-18 20:50
Fixed in v1.1.0

**Closed** 2023-09-19 18:47 UTC
Labels: bug

**Comment by mdhampton** [comment] 2023-09-20 12:09
Thank you very much!
