### ISSUE TITLE
Collection w/ zero count record group causes issues w/ xValue and data grouping

### ISSUE THREAD

**Issue by misterbee180** [apexcharts/Blazor-ApexCharts#124] opened 2022-07-12 15:33 UTC
I have the following collection of data which returns the following simple bar graph:
![image](https://user-images.githubusercontent.com/5283412/178526346-e7161c60-b8bb-4b30-bdf0-55ef6e487d45.png)

If i remove the 1 record (that was added to make this work) for onTime reliagear I get the following incorrectly generated graph
![image](https://user-images.githubusercontent.com/5283412/178526644-75ed414a-62f6-4a05-859a-3ff0b12ded80.png)

1. The xValue is missing
2. The data is now grouped incorrectly, w/ safegear now containing reliagears late records (red) and safegears count going over to (missing) reliagear column

Here is my chart configuration:
![image](https://user-images.githubusercontent.com/5283412/178527728-c8e0159f-9599-40d3-8c8c-747f4489e102.png)

It seems like the xValue is only ever established from the first point series of an apex chart and that if the count of the filtered collection for a point series is 0 it isn't able to establish it properly. In addition it is not trying to pull the value from further point series.

**Comment by joadan** [comment] 2022-07-14 12:18
Hi,

Thank you for reporting.

Short answer is that currently this is by design.

The wrapper is not doing anything in order to match the x axis data, but rather just sends it as is down to apexcharts.js. Apexchart expects the all data to have X-axis values.

I think that we should be able to fix this in the wrapper.
I'm on vaccation and have some problem access my developer machine so I can't dig into this right now.

For now you would have to make sure all data have the same x axis values.
I will look into this but I can't commit to when/if it will be fixed.

**Comment by misterbee180** [comment] 2022-07-14 14:13
Hey Joadan, thanks for the confirmation. 

I'll throw some logic around the various data sources myself for the time being to make sure that we have those x-axis values there.

**Comment by joadan** [comment] 2022-10-04 18:48
#158

**Closed by joadan** 2022-10-04 18:48 UTC
